# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    orders.file_renderer:
        class:      AppBundle\Util\Order\FileRenderer
        arguments:  ["@templating"]
